# Generated by Django 3.0.3 on 2020-02-08 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address1', models.CharField(max_length=512)),
                ('Address2', models.CharField(max_length=512, null=True)),
                ('City', models.CharField(max_length=256)),
                ('State', models.CharField(max_length=32)),
                ('Zip', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('TaxID', models.CharField(max_length=16)),
                ('Phone', models.CharField(max_length=16)),
                ('NAICS', models.CharField(max_length=8)),
                ('HasBeenProfitable', models.BooleanField(default=False)),
                ('HasBankruptedInLast7Years', models.BooleanField(default=True)),
                ('InceptionDate', models.DateTimeField()),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Address')),
            ],
        ),
        migrations.CreateModel(
            name='CFApplicationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestedLoanAmount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('StatedCreditHistory', models.IntegerField()),
                ('LegalEntityType', models.CharField(max_length=16)),
                ('FilterID', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='RequestHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CFRequestId', models.CharField(max_length=32)),
                ('RequestDate', models.DateTimeField()),
                ('CFApiUserId', models.CharField(max_length=32, null=True)),
                ('CFApiPassword', models.CharField(max_length=128, null=True)),
                ('IsTestLead', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SelfReportedCashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnnualRevenue', models.DecimalField(decimal_places=2, max_digits=16)),
                ('MonthlyAverageBankBalance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('MonthlyAverageCreditCardVolume', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32)),
                ('FirstName', models.CharField(max_length=32)),
                ('LastName', models.CharField(max_length=32)),
                ('Email', models.CharField(max_length=64)),
                ('DateOfBirth', models.DateTimeField()),
                ('HomePhone', models.CharField(max_length=16)),
                ('SSN', models.CharField(max_length=9)),
                ('PercentageOfOwnership', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('HomeAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Address')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.Business')),
                ('CFApplicationData', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.CFApplicationData')),
                ('Owners', models.ManyToManyField(to='loans.Owner')),
                ('RequestHeader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.RequestHeader')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='SelfReportedCashFlow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.SelfReportedCashFlow'),
        ),
    ]
