# Generated by Django 3.0.3 on 2020-02-09 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='Address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.Address'),
        ),
        migrations.AlterField(
            model_name='business',
            name='SelfReportedCashFlow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.SelfReportedCashFlow'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
